### ISSUE TITLE
Latest version of VSCode causes endless loop between inserting new line and saving

### ISSUE THREAD

**Issue by ConduciveMammal** [riccardoNovaglia/vsCodeBlankLine#10] opened 2017-10-09 09:25 UTC
I've just updated to VSCode V 1.17.0 and there seems to be a bug that causes an endless save loop. Looking at the bottom of the file, the new blank line seems to be getting added, saved, and then removed and saved so on and so forth.

I can't be sure if it's all files, I'm seeing this in *.liquid files.

**Comment by riccardoNovaglia** [comment] 2017-10-09 09:30
Thanks for the update! I'll have a look after work. Sorry about the issue!

Riccardo

**Comment by riccardoNovaglia** [comment] 2017-10-09 12:15
Is this a duplicate of #7? What os are you running on?

**Comment by ConduciveMammal** [comment] 2017-10-09 16:55
Hey man,
That’s no problem at all.

It seems to be the same thing occurring, but that original issue is from 5 months ago, but for me it only started yesterday after I updated VSC. It happened on both my home and work computer so it’s unlilely to be a singular case.

Both systems are running Windows 10.

Thanks

**Comment by riccardoNovaglia** [comment] 2017-10-09 16:59
Thanks for the reply. I think it's likely to be similar or related. As I
mentioned unfortunately I don't have a windows machine to test that on, so
not really sure how to address it myself.

I reckon the issue is with this function, but without a machine to test it
I'd be making changes blindly:

```
private saveFile(callback) {

        // This timeout is a hack to ensure that the file edit is complete

        // before saving the file. Removing it would cause VSCode to not
save the file after appending the blank line

        setTimeout(() => {

            if (this.doc.isDirty) {

                this.doc.save().then(

                    (wasSaved) => {

                        callback(wasSaved);

                    });

            } else {

                callback(true);

            }

        }, 100);

    }

```

**Comment by raphaelbadia** [comment] 2017-10-11 13:58
Hello,
I can reproduce it on mac. I think your extension have a conflict with the setting`"editor.formatOnSave": true`.
The formatOnSave setting removes any blank line in config files and your extension tries to add one, that's why it loops !
IDK how to fix it but maybe you will be able to reproduce it

**Comment by riccardoNovaglia** [comment] 2017-10-11 14:00
Awesome! It might be that I can see if that property is set and let the
user know before it happens! Thanks for letting me know

**Comment by raphaelbadia** [comment] 2017-10-11 14:02
Thank you for developing this extension 💯

**Comment by riccardoNovaglia** [comment] 2017-10-11 18:16
Just pushed the fix and published the new version! MASSIVE THANKS AGAIN!

You can now list file extensions that should be ignored. That should sort out the issue.

@ConduciveMammal I've included `.liquid` as a default, so it should fix your issue immediately.
@raphaelbadia Thanks for finding out what the hell was happening!

**Comment by ConduciveMammal** [comment] 2017-10-12 08:52
Hey @riccardoNovaglia ,
Not sure if the update was pushed yet, I just re-enabled the plugin and it's still occurring on SCSS files. Doesn't seem to happen with JS or CSS files.

**Comment by riccardoNovaglia** [comment] 2017-10-12 08:57
By default I'm only excluding a couple of file extensions, you might need
to add .scss Let me know if that solved the issue

**Comment by julkwiec** [comment] 2017-10-12 09:01
The issue happens when line endings are set to `CRLF`:
![image](https://user-images.githubusercontent.com/12023480/31488000-aa9f7c78-af3c-11e7-97a7-13c0b0825762.png)
Switching to `LF` fixes the issue :)

**Comment by riccardoNovaglia** [comment] 2017-10-12 09:05
Interesting! I'll have a look at that too! Thanks for reporting it!

**Comment by alanaasmaa** [comment] 2017-11-12 11:10
I have also same probelem. Windows 10 Pro 64bit

Switching to LF also fixes this for me.

**Comment by alanaasmaa** [comment] 2017-11-19 11:24
I found these. VsCode can add newlines nativly

```
    "files.trimTrailingWhitespace": true,
    "files.trimFinalNewlines": true,
    "files.insertFinalNewline": true
```

**Comment by riccardoNovaglia** [comment] 2017-11-19 11:27
Alright, it seems they finally caught up and added it. It's been a long time coming. Thanks for letting me know. I'll close these and the other comments, I guess this extension has reach the end of its life 😄

**Closed as completed by riccardoNovaglia** 2017-11-19 11:27 UTC
Labels: bug, duplicate, help wanted

**Comment by raphaelbadia** [comment] 2017-11-19 11:30
😄
